config/routes.rb
ToglAdmin::Application.routes.draw do
  root "promotions#index"

  resources :user_sessions, only: [:new, :create] 
  delete "/logout", to: "user_sessions#destroy", as: "logout"
  

  resources :games, only: [] do
    resources :contest_templates, only: [:index] do
      resources :event_participants, only: [:index]
    end

    resources :event_sets, only: [:index] do
      resources :event_participants, only: [:index]
    end
  end

  resources :other_tools, only: [:index]

  resources :contest_seeds, only: [:new, :index, :edit, :create, :update, :destroy]

  resources :promotions, only: [:new, :index, :show, :edit, :create, :update] do
    collection do
      get "identifier_check"
      put "update_by_identifier"
    end
  end

  resources :users, only: [] do
    collection do
      get "search"
      get "search_csv"
      get "identity_lookup"
      get "contests_lookup"
    end
    member do
      patch "enable"
      patch "disable"
    end
  end

  post "/user_contests/:id/leave", to: "user_contests#leave"

  get "/rapi_users/csv_list", to: "rapi_users#csv_list"
  get "/rapi_users/search", to: "rapi_users#search", as: "rapi_user_search"

  resources :landing_pages, only: [:new, :index, :show, :edit, :create, :update]
  resources :landing_page_templates, only: [:show]
  resources :promotion_groups, only: [:new, :index, :show, :edit, :create, :update] do
    resources :promotion_group_schedules, only: [:index, :edit, :update, :create, :destroy]
    collection do
      get "list_for_schedules"
    end
  end

  get "/metrics", to: "metrics#choose_date_range"
  post "/metrics", to: "metrics#view"

  put "/client_apps" => "application#update_client_app"

end

app/controllers/other_tools_controller.rb
class OtherToolsController < ApplicationController
  before_filter :require_user

  require 'net/http'
  require 'uri'

  def index
    
  end
end

app/views/other_tools/index.html.erb
<table>
  <tr>
    <th>Available Tools</th>
    <th>&nbsp;</th>
  </tr>
  <tr><td><%= link_to "Contest Seeds", contest_seeds_path %></td></tr>
  <tr><td><%= link_to "Metrics", metrics_path %></td></tr>
  <tr><td><%= link_to "User Management", search_users_path %></td></tr>
  <tr><td><%= link_to "User Identity Lookup", { controller: :users, action: :identity_lookup } %></td></tr>
  <tr><td><%= link_to "Leave Contest", { controller: :users, action: :contests_lookup } %></td></tr>
</table>