config/routes.rb
ToglAdmin::Application.routes.draw do
  root "promotions#index"

  resources :user_sessions, only: [:new, :create] 
  delete "/logout", to: "user_sessions#destroy", as: "logout"
  

  resources :games, only: [] do
    resources :contest_templates, only: [:index] do
      resources :event_participants, only: [:index]
    end

    resources :event_sets, only: [:index] do
      resources :event_participants, only: [:index]
    end
  end

  resources :other_tools, only: [:index]

  resources :contest_seeds, only: [:new, :index, :edit, :create, :update, :destroy]

  resources :promotions, only: [:new, :index, :show, :edit, :create, :update] do
    collection do
      get "identifier_check"
      put "update_by_identifier"
    end
  end

  resources :users, only: [] do
    collection do
      get "search"
      get "search_csv"
      get "identity_lookup"
      get "contests_lookup"
    end
    member do
      patch "enable"
      patch "disable"
    end
  end

  post "/user_contests/:id/leave", to: "user_contests#leave"

  get "/rapi_users/csv_list", to: "rapi_users#csv_list"
  get "/rapi_users/search", to: "rapi_users#search", as: "rapi_user_search"

  resources :landing_pages, only: [:new, :index, :show, :edit, :create, :update]
  resources :landing_page_templates, only: [:show]
  resources :promotion_groups, only: [:new, :index, :show, :edit, :create, :update] do
    resources :promotion_group_schedules, only: [:index, :edit, :update, :create, :destroy]
    collection do
      get "list_for_schedules"
    end
  end

  get "/metrics", to: "metrics#choose_date_range"
  post "/metrics", to: "metrics#view"

  put "/client_apps" => "application#update_client_app"

end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic do |config|
    config.crypto_provider = Authlogic::CryptoProviders::Sha512
    config.transition_from_crypto_providers = Authlogic::CryptoProviders::BCrypt
    config.require_password_confirmation = true
    config.login_field = :email
  end

  def self.find_by_email_or_persistence_token(login)
    find_by("LOWER(email) = ?", login.to_s.downcase) || find_by_persistence_token(login.to_s)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search
    @user_results = RapiManager.new.search_users(params[:query])
  end

  def identity_lookup
    @user_uuid = params[:user_uuid]
    if @user_uuid.present?
      @identity_information = RapiManager.new.lookup_user_identity(@user_uuid)
    end
  end

  def contests_lookup
    if params[:username].present?
      @contest_results = RapiManager.new.lookup_user_contests_by_username(params[:username])
      # It gets here and is present and not nil
    elsif params[:uuid].present?
      @contest_results = RapiManager.new.lookup_user_contests_by_uuid(params[:uuid])
    elsif params[:email].present?
      @contest_results = RapiManager.new.lookup_user_contests_by_email(params[:email])
    end
  end

  def search_csv
    send_data RapiManager.new.search_users_csv(params[:query]), type: Mime::CSV, disposition: "attachment; filename=users.csv"
  end

  def enable
    RapiManager.new.update_user(params[:id], { user: { state: "active" }}.to_json)
    redirect_to :back
  end

  def disable
    RapiManager.new.update_user(params[:id], { user: { state: "disabled" }}.to_json)
    redirect_to :back
  end
end

app/views/users/contests_lookup.html.erb
<%= form_tag "/users/contests_lookup", method: :get do %>
  <%= label_tag :username, "Lookup by Username" %><br/>

  <br/>
  <%= text_field_tag :username, params[:username] %>
  <%= submit_tag "Search by Username" %>
  <br/>
  <br/>
<%- end %>
<%= form_tag "/users/contests_lookup", method: :get do %>
  <%= label_tag :uuid, "Lookup by UUID" %><br/>

  <br/>
  <%= text_field_tag :uuid, params[:uuid] %>
  <%= submit_tag "Search by UUID" %>
  <br/>
  <br/>
<%- end %>
<%= form_tag "/users/contests_lookup", method: :get do %>
  <%= label_tag :email, "Lookup by Email" %><br/>

  <br/>
  <%= text_field_tag :email, params[:email] %>
  <%= submit_tag "Search by Email" %>
  <br/>
<%- end %>


<br/>
<br/>
<br/>
<br/>
<%- if @contest_results.present? %>
  <table>
    <tr>
      <td>ID</td>
      <td>Game</td>
      <td>Event Set</td>
      <td>Lock Time</td>
      <td>Entries</td>
      <td>Size</td>
      <td>Buyin</td>
      <td>&nbsp;</td>
    </tr>
  <%- @contest_results.each do |result| %>
    <tr>
      <td><%= result["id"] %></td>
      <td><%= result["game"] %></td>
      <td><%= result["event_set"] %></td>
      <td><%= Time.parse(result["lock_time"]).in_time_zone("America/Los_Angeles") %></td>
      <td><%= result["num_entries"] %></td>
      <td><%= result["size"] %></td>
      <td><%= result["buy_in"] %></td>
      <td><%= link_to "Cancel", "/user_contests/#{result['id']}/leave", method: :post, confirm: "Sure?"  %></td>
    </tr>
  <%- end %>
  </table>
  <br/>
<%- else %>
  <p>
  No Results
  </p>
<%- end %>

app/views/users/identity_lookup.html.erb
<%= form_tag "/users/identity_lookup", method: :get do %>
  <%= label_tag :user_uuid, "User UUID" %><br/>
  <small>
    Provide User UUID and get the goods
  </small><br/>
  
  <br/>
  <br/>
  <%= text_field_tag :user_uuid, params[:user_uuid] %>
  <%= submit_tag "Search" %>
  <br/>
<%- end %>

<br/>
<br/>
<br/>
<br/>
<%- if @identity_information.present? %>
  <table>
    <tr><td>Timestamp: <%= @identity_information["created_at"] %></td></tr>
    <tr><td>Successful?: <%= @identity_information["was_successful"] %></td></tr>
    <tr><td>Full Name: <%= @identity_information["request"]["FullName"] %></td></tr>
    <tr><td>Birthdate: <%= @identity_information["request"]["DateOfBirth"] %></td></tr>
    <tr><td>Address: <%= @identity_information["request"]["AddressLine1"] %></td></tr>
    <tr><td>City: <%= @identity_information["request"]["City"] %></td></tr>
    <tr><td>Postal Code: <%= @identity_information["request"]["PostalCode"] %></td></tr>
    <tr><td>State Code: <%= @identity_information["request"]["StateCode"] %></td></tr>
    <tr><td>Country Code: <%= @identity_information["request"]["CountryCode"] %></td></tr>
    <tr><td>Identity Confidence Score: <%= @identity_information["response"]["IdentityConfidenceScore"] %></td></tr>
    <tr><td>Fraud Confidence Score: <%= @identity_information["response"]["FraudConfidenceScore"] %></td></tr>
    <tr><td>Response Code: <%= @identity_information["response"]["ResponseCode"] %></td></tr>
    <tr><td>Response Message: <%= @identity_information["response"]["ResponseMessage"] %></td></tr>
    <tr><td>Location Detail: <%= @identity_information["response"]["LocationDetail"] %></td></tr>
    <tr><td>Reason Codes: <%= @identity_information["response"]["ReasonCodes"] %></td></tr>
    <tr><td>&nbsp;</td></tr>
  </table>
<%- else %>
  <p>
  No Results
  </p>
<%- end %>

app/views/users/search.html.erb
<%= form_tag "/users/search", method: :get do %>
  <%= label_tag :query, "User Search" %><br/>
  <small>
    Search by uuid, email, username, ip, promo code, promotions, and/or promotion group. Search multiple terms by separating them with commas
  </small><br/>
  
  <small><em>
    Limited to first 100 results. Request csv for full download.
  </em></small>
  
  <br/>
  <br/>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "Search" %>
  <br/>
<%- end %>


<br/>
<br/>
<br/>
<br/>
<%- if @user_results.present? %>
  <table>
    <tr>
      <td>ID</td>
      <td>Status</td>
      <td>UUID</td>
      <td>Username</td>
      <td>Email</td>
      <td>Current Ip</td>
      <td>Previous Ip</td>
      <td>Relationship</td>
      <td>&nbsp;</td>
    </tr>
  <%- @user_results.each do |result| %>
    <tr>
      <td><%= result["id"] %></td>
      <td><%= result["state"] %></td>
      <td><%= result["uuid"] %></td>
      <td><%= result["username"] %></td>
      <td><%= result["email"] %></td>
      <td><%= result["current_login_ip"] %></td>
      <td><%= result["last_login_ip"] %></td>
      <td><%= result["relationship"] %></td>
      <td>
        <%- if result["state"] == "active" %>
          <%= link_to "Disable", disable_user_path(result["id"]), method: :patch, confirm: "Sure?"  %>
        <%- elsif result["state"] == "disabled" %>
          <%= link_to "Activate", enable_user_path(result["id"]), method: :patch, confirm: "Sure?" %>
        <%- end %>
      </td>
    </tr>
  <%- end %>
  </table>
  <br/>
  <%= link_to "Download CSV", search_csv_users_path(query: params[:query]) %>
<%- else %>
  <p>
  No Results
  </p>
<%- end %>