config/routes.rb
ToglAdmin::Application.routes.draw do
  root "promotions#index"

  resources :user_sessions, only: [:new, :create] 
  delete "/logout", to: "user_sessions#destroy", as: "logout"
  

  resources :games, only: [] do
    resources :contest_templates, only: [:index] do
      resources :event_participants, only: [:index]
    end

    resources :event_sets, only: [:index] do
      resources :event_participants, only: [:index]
    end
  end

  resources :other_tools, only: [:index]

  resources :contest_seeds, only: [:new, :index, :edit, :create, :update, :destroy]

  resources :promotions, only: [:new, :index, :show, :edit, :create, :update] do
    collection do
      get "identifier_check"
      put "update_by_identifier"
    end
  end

  resources :users, only: [] do
    collection do
      get "search"
      get "search_csv"
      get "identity_lookup"
      get "contests_lookup"
    end
    member do
      patch "enable"
      patch "disable"
    end
  end

  post "/user_contests/:id/leave", to: "user_contests#leave"

  get "/rapi_users/csv_list", to: "rapi_users#csv_list"
  get "/rapi_users/search", to: "rapi_users#search", as: "rapi_user_search"

  resources :landing_pages, only: [:new, :index, :show, :edit, :create, :update]
  resources :landing_page_templates, only: [:show]
  resources :promotion_groups, only: [:new, :index, :show, :edit, :create, :update] do
    resources :promotion_group_schedules, only: [:index, :edit, :update, :create, :destroy]
    collection do
      get "list_for_schedules"
    end
  end

  get "/metrics", to: "metrics#choose_date_range"
  post "/metrics", to: "metrics#view"

  put "/client_apps" => "application#update_client_app"

end

app/models/contest_seed.rb
class ContestSeed < ActiveRecord::Base
  validates_presence_of :game_identifier
  validates_presence_of :size
  validates_presence_of :buy_in
  validates_presence_of :minutes_before_lock_cutoff

  validates_uniqueness_of :game_identifier, scope: [:size, :buy_in], message: "Game identifier, size, buy_in combination already exists"

  before_create :set_defaults, on: :create


  private

  def set_defaults
    self.minutes_before_lock_cutoff = 60 if self.minutes_before_lock_cutoff.nil?
    self.is_active = true if self.is_active.nil?
  end
end

app/controllers/contest_seeds_controller.rb
class ContestSeedsController < ApplicationController
  before_filter :require_user
  before_filter :get_games, except: [:index, :destroy]
  def index
    @contest_seeds = ContestSeed.all.sort_by do |contest_seed|
      [contest_seed.game_identifier, contest_seed.size, contest_seed.buy_in]
    end
  end

  def new
    @contest_seed = ContestSeed.new
  end

  def create
    @contest_seed = ContestSeed.new(params[:contest_seed].permit(:game_identifier, :size, :buy_in, :minutes_before_lock_cutoff))
    if @contest_seed.save
      flash.keep[:notice] = "Contest seed created!"
      redirect_to contest_seeds_path
    else
      flash.now[:error] = @contest_seed.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @contest_seed = ContestSeed.find(params[:id])
  end

  def update
    @contest_seed = ContestSeed.find(params[:id])
    @contest_seed.update(params[:contest_seed].permit(:game_identifier, :size, :buy_in, :minutes_before_lock_cutoff))
    if @contest_seed.save
      flash.keep[:notice] = "Contest seed updated!"
      redirect_to contest_seeds_path
    else
      flash.now[:error] = @contest_seed.errors.full_messages.join(", ")
      render :new
    end
  end

  def destroy
    @contest_seed = ContestSeed.find(params[:id])
    @contest_seed.destroy!
    flash.keep[:notice] = "Contest seed DESTROYED!"
    redirect_to contest_seeds_path
  end

private
  def get_games
    rapi_response = RapiManager.new.list_games
    @games = rapi_response["games"].collect do |game|
      game["identifier"]
    end
  end
end

app/views/contest_seeds/_form.html.erb
<%= form_for @contest_seed do |f| %>

  <%= f.label :game_identifier, "Game" %><br/>
  <%= f.select :game_identifier, @games %><br/>
  <%= f.label :size, "Contest Size" %><br/>
  <%= f.select :size, [2, 3, 5, 10] %><br/>
  <%= f.label :buy_in, "Buy In" %><br/>
  <%= f.select :buy_in, 
    [
      ["FREE", 0],
      ["$1", 100],
      ["$2", 200],
      ["$5", 500],
      ["$10", 1000],
      ["$20", 2000],
      ["$50", 5000],
      ["$100", 10000]
    ] %><br/>

  <%= f.label :minutes_before_lock_cutoff, "Cutoff Before Lock Time" %><br/>
  <%= f.number_field :minutes_before_lock_cutoff %> minutes<br/>


  <br/>

  <%= f.submit "Submit" %>

<% end %>

app/views/contest_seeds/edit.html.erb
<h1>A Contest Seed to Edit</h1>
<%= render partial: "form" %>

app/views/contest_seeds/index.html.erb
<%= link_to "New Contest Seed", new_contest_seed_path %>


<br/>
<br/>
<table>
  <tr>
    <th>Game</th>
    <th>Contest Size</th>
    <th>Buy In</th>
    <th>Lock Time Cutoff</th>
    <th>Active?</th>
    <th>&nbsp;</th>
  </tr>
<%- @contest_seeds.each do |contest_seed| %>
  <tr>
    <td>
      <%= contest_seed.game_identifier %>
    </td>
    <td>
      <%= contest_seed.size %>
    </td>
    <td>
      <%= "$%0.2f" % (contest_seed.buy_in / 100.0) %>
    </td>
    <td>
      <%= distance_of_time_in_words(contest_seed.minutes_before_lock_cutoff.minutes) %>
    </td>
    <td>
      <%= contest_seed.is_active? ? "YES" : "NO" %>
    </td>
    <td>
      <%= link_to "Edit", edit_contest_seed_path(contest_seed.id) %>
      <%= link_to "Delete", contest_seed_path(contest_seed.id), method: :delete, confirm: "Sure?" %>
    </td>
  </tr>
<%- end %>
</table>

app/views/contest_seeds/new.html.erb
<h1>A New Contest Seed</h1>
<%= render partial: "form" %>