config/routes.rb
ToglAdmin::Application.routes.draw do
  root "promotions#index"

  resources :user_sessions, only: [:new, :create] 
  delete "/logout", to: "user_sessions#destroy", as: "logout"
  

  resources :games, only: [] do
    resources :contest_templates, only: [:index] do
      resources :event_participants, only: [:index]
    end

    resources :event_sets, only: [:index] do
      resources :event_participants, only: [:index]
    end
  end

  resources :other_tools, only: [:index]

  resources :contest_seeds, only: [:new, :index, :edit, :create, :update, :destroy]

  resources :promotions, only: [:new, :index, :show, :edit, :create, :update] do
    collection do
      get "identifier_check"
      put "update_by_identifier"
    end
  end

  resources :users, only: [] do
    collection do
      get "search"
      get "search_csv"
      get "identity_lookup"
      get "contests_lookup"
    end
    member do
      patch "enable"
      patch "disable"
    end
  end

  post "/user_contests/:id/leave", to: "user_contests#leave"

  get "/rapi_users/csv_list", to: "rapi_users#csv_list"
  get "/rapi_users/search", to: "rapi_users#search", as: "rapi_user_search"

  resources :landing_pages, only: [:new, :index, :show, :edit, :create, :update]
  resources :landing_page_templates, only: [:show]
  resources :promotion_groups, only: [:new, :index, :show, :edit, :create, :update] do
    resources :promotion_group_schedules, only: [:index, :edit, :update, :create, :destroy]
    collection do
      get "list_for_schedules"
    end
  end

  get "/metrics", to: "metrics#choose_date_range"
  post "/metrics", to: "metrics#view"

  put "/client_apps" => "application#update_client_app"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TopLine Game Labs: Administrative Edition</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div id="heading" style="padding: 18px 12px; margin: 0;">
  <div id="main_nav" style="float: left">
    1. <%= link_to "Landing Page", landing_pages_path %>
    &nbsp;
    2. <%= link_to "Promotion Group", promotion_groups_path %>
    &nbsp;
    3. <%= link_to "Promotion Group Scheduling", list_for_schedules_promotion_groups_path %>
    &nbsp;
    4. <%= link_to "Promotion", promotions_path %>
    &nbsp;
    Bonus: <%= link_to "Email List", "https://s3-us-west-2.amazonaws.com/dailymvp-assets/reports/#{Rails.env}_user_list.csv" %>
    &nbsp;
    Bonus 2: <%= link_to "Other Tools", other_tools_path %>
  </div>


  <div id="user_nav" style="float: right">
    <% if current_user %>
      <%= current_user.email %> | <%= link_to "Logout", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>

  <div id="client_app_nav" style="float: right">
    <%= label_tag :client_app, "Client" %>
    <%= select_tag :client_app, options_for_select(["dailymvp", "fannation"], @current_client_app), onchange: "update_client_app();", disabled: !@allow_client_app_selector %>
    &nbsp;
    &nbsp;
  </div>
  <div style="clear: both"></div>
</div>

<hr/>
<br/>

<%- if flash[:error] %>
  <div style="color: red;">
    <strong>Error! </strong>
    <%= flash[:error] %>
    <br/>
    <br/>
  </div>
<%- end %>
<%- if flash[:notice] %>
  <div style="color: green;">
    <strong>Hey! </strong>
    <%= flash[:notice] %>
    <br/>
    <br/>
  </div>
<%- end %>

<%= yield %>



</body>
</html>



<script type="text/javascript">
  $(document).ready(function() {
    update_ui_for_client_app();
  });
</script>